//MAINCONTENT TYPES
export const SET_APP_CONTENT = "SET_APP_CONTENT";
export const FETCH_MOVIES_MAINCONTENT = "FETCH_MOVIES_MAINCONTENT";
export const FETCH_WHATSSHOWING_MOVIESUMMARY = "FETCH_WHATSSHOWING_MOVIESUMMARY";

//HEADER TYPES
export const FETCH_GENRES = "FETCH_GENRES";
export const FETCH_MOSTPOPULAR_MOVIE = "FETCH_MOSTPOPULAR_MOVIE";

//MOVIESUMMARY TYPES
export const FETCH_GENRES_MOVIESUMMARY = "FETCH_GENRES_MOVIESUMMARY";
export const FETCH_MOVIE_MOVIESUMMARY = "FETCH_MOVIE_MOVIESUMMARY";
export const FETCH_REVIEWS_MOVIESUMMARY = "FETCH_REVIEWS_MOVIESUMMARY";
export const FETCH_CAST_MOVIESUMMARY = "FETCH_CAST_MOVIESUMMARY";
export const FETCH_VIDEOS_MOVIESUMMARY = "FETCH_VIDEOS_MOVIESUMMARY";
export const FETCH_SIMILARMOVIES_MOVIESUMMARY = "FETCH_SIMILARMOVIES_MOVIESUMMARY";

//ACTORSUMMARY TYPES
export const FETCH_ACTOR_ACTORSUMMARY = "FETCH_ACTOR_ACTORSUMMARY";
export const FETCH_CREDITS_ACTORSUMMARY = "FETCH_CREDITS_ACTORSUMMARY";

//MODAL TYPES
export const SET_ACTIVITY = "SET_ACTIVITY";
export const MODAL_VISIBILITY = "MODAL_VISIBILITY";